services:

  http_service:
    volumes:
      - ./src/php_fpm_service:/usr/src/php_fpm_service
    restart: "no"

  php_fpm_service:
    build:
      target: debug
    volumes:
      - ./src/php_fpm_service:/usr/src/php_fpm_service # mount source, so it's possible to modify it without restarting the service
    extra_hosts:
      - host.docker.internal:host-gateway # for xdebug
    restart: "no"

  deno_service:
    build:
      target: debug
    volumes:
      - ./src/deno_service:/usr/src/deno_service # mount source, so it's possible to modify it and restart this service without rebuilding the image: `docker restart docker-vscode-debug-example_deno_service_1`
    ports:
      - 5090:5090 # app service port
      - 48050:48050 # debugger port
    restart: "no"

  node_service:
    build:
      target: debug
    volumes:
      - ./src/node_service:/usr/src/node_service # mount source, so it's possible to modify it and restart this service without rebuilding the image: `docker restart docker-vscode-debug-example_node_service_1`
    ports:
      - 12982:12982 # app service port
      - 8548:8548 # debugger port
    restart: "no"

  rust_service:
    build:
      target: debug
    ports:
      - 9023:9023 # app service port
      - 29935:29935 # lldb-server listens for connections
      - 18088:18088 # lldb-server service port
    restart: "no"
    privileged: true

  swift_service:
    build:
      target: debug
    ports:
      - 15880:15880 # app service port
      - 2418:2418 # lldb-server listens for connections
      - 16276:16276 # lldb-server service port
    restart: "no"
    privileged: true

  c_service:
    build:
      target: debug
    ports:
      - 8543:8543 # app service port
      - 2201:2201 # lldb-server listens for connections
      - 9850:9850 # lldb-server service port
    restart: "no"
    privileged: true

  dotnet_service:
    build:
      target: debug
    ports:
      - 7287:7287 # app service port
    restart: "no"

  java_service:
    build:
      target: debug
    ports:
      - 27712:27712 # app service port
      - 9455:9455 # debugger port
    restart: "no"

  python_service:
    build:
      target: debug
    volumes:
      - ./src/python_service:/usr/src/python_service # mount source, so it's possible to modify it and restart this service without rebuilding the image: `docker restart docker-vscode-debug-example_python_service_1`
    ports:
      - 8497:8497 # app service port
      - 22742:22742 # debugger port
    restart: "no"
